# Generated by Django 4.2.23 on 2025-09-22 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0002_product_daily_deal_product_hot"),
    ]

    operations = [
        migrations.DeleteModel(name="ProductSize",),
    ]
