# Generated by Django 4.2.23 on 2025-09-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0003_delete_productsize"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="daily_deal",),
        migrations.RemoveField(model_name="product", name="hot",),
        migrations.AddField(
            model_name="product",
            name="main_image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
    ]
