# Generated by Django 4.2.23 on 2025-09-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0004_remove_product_daily_deal_remove_product_hot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="daily_deal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product", name="hot", field=models.BooleanField(default=False),
        ),
    ]
